const config = {
  REACT_APP_API_URL: 'REACT_APP_API_URL',
  REACT_APP_API_VERSION: 'REACT_APP_API_VERSION',
  REACT_APP_GMT_VN: 'REACT_APP_GMT_VN',
  REACT_APP_SALT: 'REACT_APP_SALT',
};
export default config;
