name: CI

on:
  push:
    branches:
      - develop
      - /feature.*/
  pull_request:
    branches:
      - develop
      - /feature.*/
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm run lint:staged
        npm run build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: 
          - develop
          - /feature.*/
        BRANCH: ci-cd
        FOLDER: build
